### ISSUE TITLE
Broken link on coding standards page

### ISSUE THREAD

**Issue by brentswisher** [WordPress-Coding-Standards/docs#23]
The first link of the [coding standards page](https://developer.wordpress.org/coding-standards/) to "Commit Messages" goes to a 404: https://developer.wordpress.org/coding-standards/commit-messages/

**Comment by ntwb** [comment]
Thanks @brentswisher, fixed in #24 where I've removed non-coding standards links.

p.s The current index page will also be replaced entirely in the coming days.
